### ISSUE TITLE
Is python 2.7 supported?

### ISSUE THREAD

**Issue by CARLAlover** [ucla-mobility/OpenCDA#101]
First of all, thanks for this great project, it looks amazing!  I have a question about the supported version of Python. I saw on the installation page, python 3.7 is supported, does your project also support python2.7? Thanks!

**Comment by DerrickXuNu** [comment]
Thanks for liking our project!  Unfortunately, Python2.7 is not supported currently. This is because some of our dependent packages(e.g. Open3D) don't support python 2.7.

**Comment by CARLAlover** [comment]
Thanks for the clarification! The installation with python3.7 is smooth, nice work!
