### ISSUE TITLE
Is reinforcement learning supported?

### ISSUE THREAD

**Issue by xiaoyucheri** [ucla-mobility/OpenCDA#105]
Thanks for creating this great project! I saw OpenCDA has some rule-based algorithms as planning module. So does it also support reinforcement learning behavior planning? Thanks!

**Comment by DerrickXuNu** [comment]
Yes, OpenCDA supports RL development. Pass the RL states to the behavior agent through function `update_information()`, execute the action in `run_step()` and collect the rewards in `plan_debuger()` or `EvaluationManager()`. If you are using deep RL, you can put your model in `MLManager` and add it as an attribute in your behavior agent class. Check https://opencda-documentation.readthedocs.io/en/latest/md_files/customization.html to see more details.

**Comment by xiaoyucheri** [comment]
That works, thanks!
