### ISSUE TITLE
ERROR: single_2lanefree_carla.py not found under opencda/scenario_testing

### ISSUE THREAD

**Issue by JackRen88** [ucla-mobility/OpenCDA#122]
Hello.
When I run the code `python opencda.py -t single_2lanefree_carla`.there is a error below:
`ERROR: single_2lanefree_carla.py not found under opencda/scenario_testing`. How should I solved it?

**Comment by DerrickXuNu** [comment]
It seems you may not tightly follow the installation instructions. Can you make sure when you install OpenCDA, you ran these three command?

conda env create -f environment.yml
conda activate opencda
python setup.py develop

Also, before you run any script, please active the opencda environment first.

**Comment by DerrickXuNu** [comment]
I would regard the issue is solved if no response after 3 more days. Please let me know if you still have issue.
