### ISSUE TITLE
If OpenCDA will integrate ROS or Apollo?

### ISSUE THREAD

**Issue by fzd9752** [ucla-mobility/OpenCDA#128]
Hi team,

Thanks for your great work! I just have a question about your future development plan. Does ROS/Apollo will be integrated into OpenCDA?

**Comment by DerrickXuNu** [comment]
Hi, thanks for your question!  Yes, we do plan to integrate ROS with OpenCDA in the  future. It may be another repo called OpenCDA_ros.
