### ISSUE TITLE
opencda.py: error: unrecognized arguments: -v 0.9.12

### ISSUE THREAD

**Issue by Sei2112** [ucla-mobility/OpenCDA#130]
Hi, when I changed my carla version this error occurred. Is there any mistake in my command?
```
(opencda) anyu@anyu_2019:~/OpenCDA$ python opencda.py -t single_2lanefree_carla -v 0.9.12
usage: opencda.py [-h] -t TEST_SCENARIO [--record] [--apply_ml]
opencda.py: error: unrecognized arguments: -v 0.9.12
```

**Comment by DerrickXuNu** [comment]
Hi, are you using main branch? -v arguments right now only work in develop branch and it will be merged to the main branch in 2 days.

**Comment by DerrickXuNu** [comment]
No, you can use the develop branch. Just do the following command:
`git fetch`
`git checkout develop`
 `git pull origin develop`
