### ISSUE TITLE
Can Opencda run in windows 10?

### ISSUE THREAD

**Issue by suluoniu** [ucla-mobility/OpenCDA#136]
Can Opencda run in windows 10?

**Comment by DerrickXuNu** [comment]
Yes you can. There is blog about this:

https://blog.csdn.net/fhzhu830/article/details/120613922?utm_medium=distribute.wap_aggpage_search_result.none-task-blog-2~aggregatepage~first_rank_ecpm_v1~rank_aggregation-1-120613922.wap_agg_rank_aggregation&utm_term=opencda安装

**Comment by suluoniu** [comment]
3Q
