### ISSUE TITLE
0xc4: MoveToXY vehicle should obtain: edgeID, lane, x, y, angle and optionally keepRouteFlag.

### ISSUE THREAD

**Issue by thuns001** [ucla-mobility/OpenCDA#147]
Hi All,

I was able to run the co-sim scenario with SUMO in the past weeks, however, now I receive error messages as the following.

In SUMO, this error showed up, Error: Answered with error to command 0xc4: MoveToXY vehicle should obtain: edgeID, lane, x, y, angle and optionally keepRouteFlag.

****The following error message is shown in the terminal.**** 

(opencda) 09:25:25 carma3@carma ~/OpenCDA (main) $ python opencda.py -t platoon_joining_2lanefree_cosim -v 0.9.12
OpenCDA Version: 0.1.1
load opendrive map '2lane_freeway_simplified.xodr'.
INFO - 2022-03-09 09:25:35,271 - sumo_simulation - Starting new sumo server...
INFO - 2022-03-09 09:25:35,272 - sumo_simulation - Remember to press the play button to start the simulation
 Retrying in 1 seconds
Loading configuration ... done.
Creating platoons/
Creating single CAVs.
WARNING - 2022-03-09 09:25:40,696 - bridge_helper - sumo vtype DEFAULT_VEHTYPE not found in carla. The following blueprint will be used: vehicle.chevrolet.impala
/home/carma3/anaconda3/envs/opencda/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/carma3/anaconda3/envs/opencda/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/carma3/anaconda3/envs/opencda/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/carma3/anaconda3/envs/opencda/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

Does anybody have an idea why this happened? Please help. Thank you.

**Comment by DerrickXuNu** [comment]
It works for me with the above command. What's your sumo version?
