### ISSUE TITLE
file single_2lanefree_carla.yaml miss key "activate"  

### ISSUE THREAD

**Issue by chenzhengxi** [ucla-mobility/OpenCDA#149]
file single_2lanefree_carla.yaml miss key "activate"  
  map_manager: &base_map_manager
    activate: true
    pixels_per_meter: 2
    raster_size: [224, 224]
    lane_sample_resolution: 0.1
    visualize: true

**Comment by DerrickXuNu** [comment]
Thanks for pointing this out, nice catch!

If you want, you could make a pr for this fix, otherwise, I will fix it.

**Comment by DerrickXuNu** [comment]
fixed
