### ISSUE TITLE
not found under opencda/scenario_testing

### ISSUE THREAD

**Issue by williamhatch** [ucla-mobility/OpenCDA#155]
python opencda.py -tsingle_town05_cosim -v 0.9.11 and got ERROR: single_town05_cosim.py not found under opencda/scenario_testing, any idea? @DerrickXuNu

**Comment by DerrickXuNu** [comment]
Hi, I saw you closed the issue. Have you solved the issue?

**Comment by 6Lackiu** [comment]
> python opencda​​.py -tsingle_town05_cosim -v 0.9.11 并得到错误：在opencda​​/scenario_testing下找不到single_town05_cosim.py，知道吗？@DerrickXuNu

I also encountered this problem, have you solved it?

**Comment by 6Lackiu** [comment]
> python opencda.py -tsingle_town05_cosim -v 0.9.11 and got ERROR: single_town05_cosim.py not found under opencda/scenario_testing, any idea? @DerrickXuNu

I also encountered this problem, how did you solve it? Thanks!
