### ISSUE TITLE
请问下：如果我要更换感知算法和模型，比如换yolov4，应该怎么操作，有相关说明吗

### ISSUE THREAD

**Issue by zandb2009** [ucla-mobility/OpenCDA#168]
请问下：如果我要更换感知算法和模型，比如换yolov4，应该怎么操作，有相关说明吗

**Comment by DerrickXuNu** [comment]
最简单的办法是在customize下创立你自己的perception_manager（你可以继承默认的perception_manager)，然后vehicle_manager里面不要import 默认的perception_manager, import你自己的perception_manager。只要你保证输入输出格式一样（不一样需要改相应的其他模块），可以随便替换。

**Comment by zandb2009** [comment]
好的。谢谢
