### ISSUE TITLE
目前代码里的目录检测用的yolov5的pt文件的标签好像固定的80个标签，如果我想自己指定标签应该怎么做？

### ISSUE THREAD

**Issue by zandb2009** [ucla-mobility/OpenCDA#169]
目前代码里的目录检测用的yolov5的pt文件的标签好像是固定的80个标签，我自己训练出来的模型不是按这80个标签来的，只有车辆，行人等标签，请问应该在哪里修改，才能让我的模型用例子的方法跑起来也不撞车？
例子用的：python opencda.py -t single_town06_carla  -v 0.9.13 --apply_ml

**Comment by DerrickXuNu** [comment]
在ml_manager.py里

**Comment by zandb2009** [comment]
已经测试可以了
