### ISSUE TITLE
Support for OpenCDA on Newer Ubuntu Versions

### ISSUE THREAD

**Issue by GoodarzMehr** [ucla-mobility/OpenCDA#184]
Since Both Ubuntu 18.04 and Python 3.7 are nearing EOL, I was wondering if you have any plans for adding support for newer OS, CARLA, and Python versions. I built CARLA 0.9.14 on Ubuntu 22.04 from source with Python 3.10.6 (and also other versions of Python), but none seem to work with OpenCDA.

**Comment by DerrickXuNu** [comment]
Hi,

OpenCDA supports Ubuntu20.04 + Python 3.8, and the root reason for the failure is that it doesn't support 0914 CARLA for now. We are working on upgrading this, and you will see a new big update soon.

**Comment by GoodarzMehr** [comment]
Thanks! Looking forward to the update.
