### ISSUE TITLE
How to generate annotations for LiDAR data?

### ISSUE THREAD

**Issue by 1438802682** [ucla-mobility/OpenCDA#204]
Hello, author. I would like to ask why the collected LiDAR data does not have object annotations. How can we generate annotations for LiDAR data?I hope you could find some time to look into this issue amidst your busy schedule.

**Comment by xavhl** [comment]
They are in the .yaml files (reference: [(OpenCOOD Tutorial 2: Data Annotation Introduction)](https://opencood.readthedocs.io/en/latest/md_files/data_annotation_tutorial.html)
