### ISSUE TITLE
Issue in plan_trajectory values produced by data_dumper

### ISSUE THREAD

**Issue by ch3ny1** [ucla-mobility/OpenCDA#217]
Hi there,

Thanks again for the great work! I recently am trying to use the data_dumper provided to collect some CAV data. Everything works fine except for the plan_trajectory, where some unreadable values are presented (see below). I'm using numpy=1.20.0.

Could you help give some insights on how to possibly solve this?

`RSU: false
camera0:
  cords:
  - -73.63115692138672
  - 165.252197265625
  - 1.0492979288101196
  - -0.0683288723230362
  - -101.37174987792969
  - 0.3868004083633423
  extrinsic:
  - - 1.0
    - 1.9502911065555755e-19
    - 5.155838751800809e-19
    - -3.0000124711321234
  - - -2.1693566806891167e-17
    - 1.0
    - 2.336393825525386e-19
    - -4.869623495551423e-06
  - - 2.798793495676109e-19
    - 6.475986902982072e-20
    - 1.0000000000000002
    - 0.8999999592075563
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
  intrinsic:
  - - 335.639852470912
    - 0.0
    - 400.0
  - - 0.0
    - 335.639852470912
    - 300.0
  - - 0.0
    - 0.0
    - 1.0
ego_speed: 29.953409038861125
lidar_pose:
- -73.03950500488281
- 168.1994171142578
- 1.9290239810943604
- -0.0683288723230362
- -101.37174987792969
- 0.3868004083633423
plan_trajectory:
- - -74.02294158935547
  - 163.90638732910156
  - !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      ZMsY0TyUV0A=
- - -74.31965637207031
  - 161.92794799804688
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ZMsY0TyUV0A=
- - -74.5053939819336
  - 159.83547973632812
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ZMsY0TyUV0A=
- - -74.58635711669922
  - 157.5368194580078
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ZMsY0TyUV0A=
- - -74.60906982421875
  - 155.0364532470703
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ZMsY0TyUV0A=
- - -74.61559295654297
  - 152.5365753173828
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ZMsY0TyUV0A=
- - -74.6224136352539
  - 149.83663940429688
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ZMsY0TyUV0A=
- - -74.63505554199219
  - 146.9366455078125
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ZMsY0TyUV0A=
predicted_ego_pos:
- -73.13839721679688
- 167.6962127685547
- 0.03244419023394585
- -0.0683288723230362
- -101.37174987792969
- 0.3868004083633423
true_ego_pos:
- -73.13839721679688
- 167.6962127685547
- 0.03244419023394585
- -0.0683288723230362
- -101.37174987792969
- 0.3868004083633423
vehicles:
  109:
    angle:
    - -0.0718994066119194
    - -130.9878692626953
    - 0.10898249596357346
    bp_id: vehicle.dodge.charger_police_2020
    center:
    - 0.10949905216693878
    - -1.6021728015402914e-06
    - 0.8174068927764893
    color: 0,0,0
    extent:
    - 2.6187572479248047
    - 1.0485419034957886
    - 0.819191575050354
    location:
    - -77.97999572753906
    - 138.8106689453125
    - 0.019021719694137573
    speed: 0.3370860274863887`

A side question by the way, each simulation loop uses a while True loop. Just wondering how the scenario comes to an end. Is it as soon as the first CAV hits the destination?

Thanks!

**Comment by DerrickXuNu** [comment]
Yes, it will comes to and if the first CAV reaches the destination.
