### ISSUE TITLE
Would like to have some hint on reproduce OPV2V dataset, and generate more data under same setting

### ISSUE THREAD

**Issue by lzw365-code** [ucla-mobility/OpenCDA#219]
Hello, Thanks for releasing this wonderful tool for cooperative autonomous driving research. 

I am curious about how to generate more data similar to OPV2V dataset? I saw in the OPV2V paper that there is a branch https://github.com/ucla-mobility/OpenCDA/tree/feature/data_collection, for data generation of OPV2V, but that branch is not accessible, so could you please let me know if the code is somewhere else, or whether there is a tutorial somewhere, or could you please make it accessible? 

Thanks in advance!

**Comment by DerrickXuNu** [comment]
Hi, this branch has been merged to the main branch already. Please use [v2xp_datadump_town06_carla.py](https://github.com/ucla-mobility/OpenCDA/blob/main/opencda/scenario_testing/v2xp_datadump_town06_carla.py) to collect the data.
