### ISSUE TITLE
Request for OPV2V data collection code

### ISSUE THREAD

**Issue by flow233-ai** [ucla-mobility/OpenCDA#222]
Hi! Recently I am doing some research on vehicular networks. I wonder whether there are some ways to generate a dataset like OPV2V.
I found the statement in OpenCOOD tutorial as follows:

'To help users collect customized data in CARLA (e.g., different sensor configurations and modalities) with similar data format and structure, we have released our OPV2V data collection code in the feature/data_collection branch of [OpenCDA](https://github.com/ucla-mobility/OpenCDA/tree/feature/data_collection).'

But I didn't find the "feature/data_collection" branch of OpenCDA. I wonder which part of the OpenCDA repository is now the part about data collection for OPV2V.

Thank you in advance for any help you might be able to provide.

**Comment by Oshwiciqwq** [comment]
You can see this issue https://github.com/ucla-mobility/OpenCDA/issues/219

**Comment by Oshwiciqwq** [comment]
You can see this issue https://github.com/ucla-mobility/OpenCDA/issues/219

**Comment by le-liang** [comment]
> You can see this issue #219

OK. Thank you so much.
